FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:22-alpine AS prod

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=build /app/dist /app/dist
COPY /prisma /app/prisma
COPY /doc /app/doc

COPY entrypoint.prod.sh /app/entrypoint.prod.sh

ENTRYPOINT ["/app/entrypoint.prod.sh"]